### ISSUE TITLE
Form derivation macros insists on string literals.

### ISSUE THREAD

**Issue by horned-sphere** [swimos/swim-rust#490]
**Describe the bug**
When using the `Form` derivation macro and specifying field names/enumeration tags etc, for example:
```
pub enum Envelope {
    #[form(tag = "auth")]
    Auth {
        #[form(body)]
        body: Option<Value>,
    },
    ...
}
```
the macro will only work if them name is a literal. If a constant is specified:
```
const AUTH: &str = "auth";
pub enum Envelope {
    #[form(tag = AUTH)]
    Auth {
        #[form(body)]
        body: Option<Value>,
    },
    ...
}
```
a compiler error is produced.

**Expected behavior**
The macro should accept a path to a constant string in addition to a literal.

**Comment by DobromirM** [comment]
Unfortunately it looks like this is not supported by the Rust compiler: 
https://github.com/rust-lang/rust/issues/52393#issuecomment-897952475

There is a workaround using proc macros:
https://github.com/rust-lang/rust/issues/78835#issuecomment-845831023

but apparently it is deliberately implemented to work only for the top level and not with nested attributes:
https://github.com/rust-lang/rust/issues/78835#issuecomment-845833302

**Comment by DobromirM** [comment]
As a potential workaround we can treat any uppercase string as a constant, but I am not sure how intuitive it will be.

**Comment by DobromirM** [comment]
I've tested more things and it is possible to add support for custom attributes by creating our own attribute parser instead of using the default `syn::Meta` parser. However that leads to a more complex structure and duplicates some of the code from the `syn` library. Furthermore, because constants are evaluated much later than macros there is no way to get their actual value and validation for duplicate tags will not be possible.

Example:

```rust
const TEST_TAG: &str = "test";

#[derive(Form)]
enum Foo{
    #[form(tag = "test")]
    A,
    /// There is no way to check what the actual value of TEST_TAG is.
      #[form(tag = TEST_TAG)]
    B,
}
```
